name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - devops-ci

  pull_request:
    branches:
      - devops-ci

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests yet"